"""comment relationship to user and pitch

Revision ID: 5dd5ba8f7aaa
Revises: 5be8cc51157c
Create Date: 2018-01-11 08:09:02.997530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd5ba8f7aaa'
down_revision = '5be8cc51157c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('time_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'time_posted')
    # ### end Alembic commands ###
